### ISSUE TITLE
Incorrect clone link

### ISSUE THREAD

**Issue by janmikaelr** [Aalto-LeTech/mooc-grader-course#3]
The git clone link for RST sample mooc-grader-course is incorrect and as refers to the master branch of the project:

`https://github.com/Aalto-LeTech/mooc-grader-course.git`

The Download ZIP works properly and downloads the correct RST branch.

A suggestion for a new clone link to be created (same name as for ZIP):
`https://github.com/Aalto-LeTech/mooc-grader-course-rst.git`

**Comment by teemulehtinen** [comment]
We will keep this as a branch instead of a separate repository. Therefore, git clone -b rst is required and readme updated. We are migrating to docker workflow https://github.com/apluslms/course-templates/releases
